CREATE SCHEMA if not exists recent_change_events AUTHORIZATION flink;

CREATE TABLE if not exists event (
	id bigint NOT NULL,
    "schema" varchar(32?) NULL,
    type varchar(32?) NULL,
    namespace varchar(32?) NULL,
    title varchar(32?) NULL,
    title_url varchar(32?) NULL,
    comment text NULL,
    "timestamp" timestamp NULL,
    "user" varchar(32?) NULL,
    bot boolean NULL,
    notify_url varchar(32?) NULL,
    server_url varchar(32?) NULL,
    server_name varchar(32?) NULL,
    server_script_path varchar(3?) NULL,
    wiki varchar(32?) NULL,
    parsed_comment text NULL,
    minor boolean NULL,
    patrolled boolean NULL,
    meta_uri varchar(32?) NULL,
    meta_request_id varchar(32?) NULL,
    meta_id varchar(32?) NULL,
    meta_dt varchar(32?) NULL,
    meta_domain varchar(32?) NULL,
    meta_stream varchar(32?) NULL,
    meta_topic varchar(32?) NULL,
    meta_partition integer NULL,
    meta_offset bigint NULL,
    length_old bigint NULL,
    length_new bigint NULL,
    revision_old bigint NULL,
    revision_new bigint NULL
);