CREATE SCHEMA if not exists recent_change_events AUTHORIZATION flink;

CREATE TABLE if not exists recent_change_events.event (
	id bigint NOT NULL,
    "schema" varchar(320) NULL,
    type varchar(320) NULL,
    namespace varchar(320) NULL,
    title varchar(320) NULL,
    title_url varchar(320) NULL,
    comment text NULL,
    "timestamp" timestamptz NULL,
    "user" varchar(320) NULL,
    bot boolean NULL,
    notify_url varchar(320) NULL,
    server_url varchar(320) NULL,
    server_name varchar(320) NULL,
    server_script_path varchar(30) NULL,
    wiki varchar(320) NULL,
    parsed_comment text NULL,
    minor boolean NULL,
    patrolled boolean NULL,
    meta_uri varchar(320) NULL,
    meta_request_id varchar(320) NULL,
    meta_id varchar(320) NULL,
    meta_dt varchar(320) NULL,
    meta_domain varchar(320) NULL,
    meta_stream varchar(320) NULL,
    meta_topic varchar(320) NULL,
    meta_partition integer NULL,
    meta_offset bigint NULL,
    length_old bigint NULL,
    length_new bigint NULL,
    revision_old bigint NULL,
    revision_new bigint NULL
);